using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OSSAV_WebAPI.ViewModel
{
    public class vmResidentialInput
    {

        public int? id { get; set; }
        public Nullable<int> qualified_assessor_id { get; set; }
        public Nullable<double> label_number { get; set; }
        public Nullable<int> building_id { get; set; }
        public string weather_station_location { get; set; }
        public Nullable<System.DateTime> create_label_date { get; set; }
        public string cooling_present { get; set; }
        public string source_energy_total_base { get; set; }
        public string source_energy_total_package { get; set; }
        public string source_energy_asset_base { get; set; }
        public string source_energy_asset_package { get; set; }
        public Nullable<double> base_cost { get; set; }
        public Nullable<double> package_cost { get; set; }
        public string source_eui_base { get; set; }
        public string source_eui_package { get; set; }
        public Nullable<double> base_score { get; set; }
        public Nullable<double> package_score { get; set; }
        public string site_energy_base { get; set; }
        public string site_energy_package { get; set; }
        public string site_eui_base { get; set; }
        public string site_eui_package { get; set; }
        public string carbon_base { get; set; }
        public string carbon_package { get; set; }
        public string utility_electric_base { get; set; }
        public string utility_natural_gas_base { get; set; }
        public string utility_fuel_oil_base { get; set; }
        public string utility_lpg_base { get; set; }
        public string utility_cord_wood_base { get; set; }
        public string utility_pellet_wood_base { get; set; }
        public string utility_electric_package { get; set; }
        public string utility_natural_gas_package { get; set; }
        public string utility_fuel_oil_package { get; set; }
        public string utility_lpg_package { get; set; }
        public string utility_cord_wood_package { get; set; }
        public string utility_pellet_wood_package { get; set; }
        public string utility_generated_base { get; set; }
        public string utility_generated_package { get; set; }
        public string assessment_type { get; set; }
        public Nullable<System.DateTime> assessment_date { get; set; }
        public string comments { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip_code { get; set; }
        public string shape { get; set; }
        public string town_house_walls { get; set; }
        public Nullable<int> year_built { get; set; }
        public Nullable<int> number_bedrooms { get; set; }
        public Nullable<int> num_floor_above_grade { get; set; }
        public Nullable<double> floor_to_ceiling_height { get; set; }
        public Nullable<double> conditioned_floor_area { get; set; }
        public string orientation { get; set; }
        public string blower_door_test { get; set; }
        public string air_sealing_present { get; set; }
        public string envelope_leakage { get; set; }
        public string wall_construction_same { get; set; }
        public string window_construction_same { get; set; }
        public string hvac_0_heating_type { get; set; }
        public string hvac_0_heating_fuel_primary { get; set; }
        public string hvac_0_heating_efficiency_method { get; set; }
        public Nullable<int> hvac_0_heating_year { get; set; }
        public Nullable<double> hvac_0_heating_efficiency { get; set; }
        public string hvac_0_cooling_type { get; set; }
        public string hvac_0_cooling_efficiency_method { get; set; }
        public Nullable<int> hvac_0_cooling_year { get; set; }
        public string hvac_0_cooling_efficiency { get; set; }
        public string hvac_0_hvac_name { get; set; }
        public Nullable<double> hvac_0_hvac_fraction { get; set; }
        public string hvac_1_heating_type { get; set; }
        public string hvac_1_heating_fuel_primary { get; set; }
        public string hvac_1_heating_efficiency_method { get; set; }
        public Nullable<int> hvac_1_cooling_year { get; set; }
        public Nullable<double> hvac_1_cooling_efficiency { get; set; }
        public string hvac_1_hvac_name { get; set; }
        public Nullable<double> hvac_1_hvac_fraction { get; set; }
        public string domestic_hot_water_category { get; set; }
        public string domestic_hot_water_type { get; set; }
        public string domestic_hot_water_fuel_primary { get; set; }
        public string domestic_hot_water_efficiency_method { get; set; }
        public Nullable<int> domestic_hot_water_year { get; set; }
        public string domestic_hot_water_energy_factor { get; set; }
        public string roof_0_roof_name { get; set; }
        public Nullable<double> roof_0_roof_area { get; set; }
        public string roof_0_roof_assembly_code { get; set; }
        public string roof_0_roof_color { get; set; }
        public string roof_0_roof_absorptance { get; set; }
        public string roof_0_roof_type { get; set; }
        public string roof_0_ceiling_assembly_code { get; set; }
        public Nullable<double> roof_0_skylight_area { get; set; }
        public string roof_0_skylight_method { get; set; }
        public string roof_0_skylight_code { get; set; }
        public Nullable<double> roof_0_skylight_u_value { get; set; }
        public Nullable<double> roof_0_skylight_shgc { get; set; }
        public string roof_1_roof_name { get; set; }
        public Nullable<double> roof_1_roof_area { get; set; }
        public string roof_1_roof_assembly_code { get; set; }
        public string roof_1_roof_color { get; set; }
        public string roof_1_roof_absorptance { get; set; }
        public string roof_1_roof_type { get; set; }
        public string roof_1_ceiling_assembly_code { get; set; }
        public Nullable<double> roof_1_skylight_area { get; set; }
        public string roof_1_skylight_method { get; set; }
        public string roof_1_skylight_code { get; set; }
        public Nullable<double> roof_1_skylight_u_value { get; set; }
        public Nullable<double> roof_1_skylight_shgc { get; set; }
        public string floor_0_floor_name { get; set; }
        public Nullable<double> floor_0_floor_area { get; set; }
        public string floor_0_foundation_type { get; set; }
        public string floor_0_foundation_insulation_level { get; set; }
        public string floor_0_floor_assembly_code { get; set; }
        public string floor_1_floor_name { get; set; }
        public Nullable<double> floor_1_floor_area { get; set; }
        public string floor_1_foundation_type { get; set; }
        public string floor_1_foundation_insulation_level { get; set; }
        public string floor_1_floor_assembly_code { get; set; }
        public string front_wall_assembly_code { get; set; }
        public Nullable<double> front_window_area { get; set; }
        public string front_window_method { get; set; }
        public string front_window_code { get; set; }
        public Nullable<double> front_window_u_value { get; set; }
        public Nullable<double> front_window_shgc { get; set; }
        public string back_wall_assembly_code { get; set; }
        public Nullable<double> back_window_area { get; set; }
        public string back_window_method { get; set; }
        public string back_window_code { get; set; }
        public Nullable<double> back_window_u_value { get; set; }
        public Nullable<double> back_window_shgc { get; set; }
        public string right_wall_assembly_code { get; set; }
        public Nullable<double> right_window_area { get; set; }
        public string right_window_method { get; set; }
        public string right_window_code { get; set; }
        public Nullable<double> right_window_u_value { get; set; }
        public Nullable<double> right_window_shgc { get; set; }
        public string left_wall_assembly_code { get; set; }
        public Nullable<double> left_window_area { get; set; }
        public string left_window_method { get; set; }
        public string left_window_code { get; set; }
        public Nullable<double> left_window_u_value { get; set; }
        public Nullable<double> left_window_shgc { get; set; }
        public string hvac_0_duct1_location { get; set; }
        public Nullable<double> hvac_0_duct1_fraction { get; set; }
        public string hvac_0_duct1_insulated { get; set; }
        public string hvac_0_duct1_sealed { get; set; }
        public string hvac_0_duct2_location { get; set; }
        public Nullable<double> hvac_0_duct2_fraction { get; set; }
        public string hvac_0_duct2_insulated { get; set; }
        public string hvac_0_duct2_sealed { get; set; }
        public string hvac_0_duct3_location { get; set; }
        public Nullable<double> hvac_0_duct3_fraction { get; set; }
        public string hvac_0_duct3_insulated { get; set; }
        public string hvac_0_duct3_sealed { get; set; }
        public string hvac_1_duct1_location { get; set; }
        public Nullable<double> hvac_1_duct1_fraction { get; set; }
        public string hvac_1_duct1_insulated { get; set; }
        public string hvac_1_duct1_sealed { get; set; }
        public string hvac_1_duct2_location { get; set; }
        public Nullable<double> hvac_1_duct2_fraction { get; set; }
        public string hvac_1_duct2_insulated { get; set; }
        public string hvac_1_duct2_sealed { get; set; }
        public string hvac_1_duct3_location { get; set; }
        public Nullable<double> hvac_1_duct3_fraction { get; set; }
        public string hvac_1_duct3_insulated { get; set; }
        public Nullable<double> hvac_1_duct3_sealed { get; set; }
        public string solar_electric_capacity_known { get; set; }
        public Nullable<double> solar_electric_system_capacity { get; set; }
        public Nullable<double> solar_electric_num_panels { get; set; }
        public Nullable<int> solar_electric_year { get; set; }
        public string solar_electric_array_azimuth { get; set; }
        public Nullable<int> external_building_id { get; set; }
        public string label_url { get; set; }
        public Nullable<System.DateTime> input_time { get; set; }
        public long? RecordTotal { get; set; }


    }
}