//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSSAV_WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments
    {
        public long ID { get; set; }
        public Nullable<long> TitleID { get; set; }
        public string Comment { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> CreateBy { get; set; }
    }
}
