//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OSSAV_WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XamarinDBEntities : DbContext
    {
        public XamarinDBEntities()
            : base("name=XamarinDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CmnUser> CmnUser { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<TravelPlace> TravelPlace { get; set; }
    }
}
